### ISSUE TITLE
Building from git

### ISSUE THREAD

**Issue by zcater** [ncraun/smoothscan#1]
Hi,

I have several questions here, I'm not sure if I should split them into separate issues.

I'm trying to make a git package for Archlinux. You may see the whole building script at
https://aur.archlinux.org/packages/sm/smoothscan-git/PKGBUILD

The problems...
How to properly generate the configure script from configure.am?

Thanks.

**Comment by ncraun** [comment]
Hello,

I hope you don't mind, but I edited your original issue to split it up, as there are about 3 different problems here, and I want to keep the issue tracker organized.

I use the GNU Autotools to manage smoothscan's build process. This toolchain will generate the configure script and Makefile from the configure.ac and Makefile.am input files. Because the configure and Makefile are generated files, I did not want to put them into the git repo, as different versions of autotools will make different files, and this could result in a lot of commit noise. 

To regenerate these files, you need to install autotools (automake, autoconf, etc) and run autoreconf -i in the main directory. This command will automatically invoke autoconf, automake, etc in the right order to create the configure and Makefile. 

Also you might want to package the released version. For the tarball source releases I will run autoreconf -i and they will be shipped in a ready-to-compile state with configure and Makefile.

**Comment by zcater** [comment]
Thanks.
autoreconf -i does the trick.

Sorry for the noob question.

**Comment by ncraun** [comment]
It was a good question, and I'm sure some other people ran into it, but didn't ask. Now if someone has a problem, they can see this issue and see how to do it for themselves.
